apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-health-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduler-healthcheck
  namespace: airflow
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: office-nextcloud-volume
              persistentVolumeClaim:
                claimName: scheduler-health-pvc
          containers:
          - name: scheduler-healthcheck
            image: ilhnctn/scheduler-hc:v4
            imagePullPolicy: IfNotPresent
            env:
            - name: AIRFLOW_HEALTH_ENDPOINT
              value: http://airflow-cr-web.airflow:8080/health
          restartPolicy: Never
