# Airflow database & redis config
data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: ~
    port: 5432
    db: postgres
    sslmode: disable

postgresql:
  enabled: true
  postgresqlPassword: postgres
  postgresqlUsername: postgres

# Git sync
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
  gitSync:
    enabled: true
